nandtotetris/computer-visualizer

README.md

Closes #7 
Updated `readme` file to include code styling and workflow guide. The guide is adopted from a certain company that some of our developers have experience with. We believe it is a good guide.

docs: add styling and workflow guide

---

package-lock.json
package.json

Fixes #8 
I did, `standard --fix` on the base directory, to fix the lint errors.

refactor: make the codebase to follow standard JS conventions

---

src/App.js
src/App.test.js
src/index.js
src/setupTests.js

I run `npm run lint-fix` on the base directory.

fix: codebase to follow standard format

---

README.md

fix: correct readme typos, update slack channel names

---

jsconfig.json
src/App.js
src/components/Hello.js

Closes #21 
You can check more details about absolute imports here, https://medium.com/@ktruong008/absolute-imports-with-create-react-app-4338fbca7e3d

feat: absolute file import

---

.github/issue_template.md
.github/pull_request_template.md

This PR adds  a git issue and pull request template.

feat: add issue and pull request template

---

README.md
package-lock.json
package.json

It is a build change, which fixes lint errors and format style changes before commit.
No
We should add instructions to fix lint errors and format style changes in `README`.
Run `npm run lint` to see if there is standard style guide error
Run `npm run lint-fix` to fix standard auto fixable errors
Run `npm run format` to see if there is style, format, error
Run `npm run format-fix` to fix format errors
Run `npm run format-lint-fix` to fix both lint and format errors.

build: configure husky lint-staged prettier

---

src/abstractions/software/assembler/parser/index.js
src/abstractions/software/assembler/parser/index.test.js
src/abstractions/software/assembler/parser/types.js
src/abstractions/software/assembler/parser/utils/index.js
src/abstractions/software/assembler/parser/utils/index.test.js
src/abstractions/software/assembler/parser/utils/regex.js
src/abstractions/software/assembler/parser/utils/regex.test.js

Make progress on #19 
It is a feature, which adds an assembler parser module
No
Nothing

feat: assembler parser module

---

src/abstractions/software/assembler/code/index.js

Make progress on #19 
This PR depends on #28, so It should be merged after #28 is merged.
It is a feature, which adds an assembler code module.
No
Nothing

feat: assembler code module

---

src/abstractions/software/compiler/tokenizer/JackToken.js
src/abstractions/software/compiler/tokenizer/TokenException.js
src/abstractions/software/compiler/tokenizer/index.js
src/abstractions/software/compiler/tokenizer/index.test.js
src/abstractions/software/compiler/tokenizer/types.js
src/abstractions/software/compiler/tokenizer/utils/index.js
src/abstractions/software/compiler/tokenizer/utils/index.test.js
src/abstractions/software/compiler/tokenizer/utils/regex.js
src/abstractions/software/compiler/tokenizer/utils/regex.test.js

Make progress on #32 
It's a feature which adds `JackTokenizer` module as the first step for compiler construction.
From the book section 10.3.2, JackTokenizer module.
No
Nothing

feat: add jack tokenizer

---

README.md

docs: node version requirement

---

README.md

Closes #45 
It will fix spelling and placement error from the previous PR #42 
No it doesn't
Nothing

docs: update node version requirement placement and fix typo

---

package.json

It's a build PR which configures standard to understand the latest es6 features like class properties... 
https://standardjs.com/#how-do-i-use-experimental-javascript-es-next-features
Since `babel-eslint` package has already installed with `react-scripts` package, we don't need to install it again.
No
Nothing

build: configure standard to understand latest es6 features

---

package-lock.json
package.json
src/App.js
src/components/codemirror/index.js
src/index.js

The motivate of this PR is to introduce a code writing utility into our react app. For this CodeMirror is chosen but CodeMirror is only available for vanilla javascript therefore we will be using a react wrapper  [https://github.com/scniro/react-codemirror2](react-codemirror2)

Setting up CodeMirror which allows users to write a code on the browser

---

src/App.test.js
src/abstractions/hardware/ALU/index.js
src/abstractions/hardware/ALU/index.test.js
src/abstractions/hardware/ALU/util/index.js
src/abstractions/hardware/ALU/util/index.test.js
src/abstractions/hardware/AND/index.js
src/abstractions/hardware/AND/index.test.js
src/abstractions/hardware/Not/index.js
src/abstractions/hardware/Not/index.test.js

It's a feature PR which adds an ALU hardware component for assembler abstraction. 
No
Nothing

feat: add ALU hardware component

---

src/abstractions/hardware/ROM32K/exception.js
src/abstractions/hardware/ROM32K/index.js
src/abstractions/hardware/ROM32K/index.test.js

It's a feature PR which adds ROM32K hardware component for the assembly process.
No
Nothing

feat: add ROM32K hardware component

---

src/abstractions/hardware/Memory/exception.js
src/abstractions/hardware/Memory/index.js
src/abstractions/hardware/Memory/index.test.js
src/abstractions/hardware/ROM32K/exception.js
src/abstractions/hardware/ROM32K/index.js

it's a feature PR which adds a memory hardware component
As specified in the book, figure 5.7 Data memory.
No
Nothing

feat: add memory hardware component

---

package-lock.json
package.json
src/App.css
src/App.js
src/components/Badge/index.js
src/components/Badge/styled.js
src/components/Buttons/index.js
src/components/CodeEditor/index.js
src/components/CodeEditor/styled.js
src/components/CommentRemover/index.js
src/components/CompilerFirstStage/index.js
src/components/CompilerFirstStage/styled.js
src/components/CompilerFirstStage/util.js
src/components/Tokenizer/index.js
src/components/Tokenizer/styled.js
src/index.js

It's a feature PR which adds the first stage of a compiler simulator. Jack code => Removes Jack code => Tokenizer
No
Nothing

feat: add first stage compiler simulator

---

src/components/CompilerFirstStage/styled.js

A fix PR which fixes responsiveness issue.

fix: use percentage instead of pixel in compiler stage one

---

package-lock.json
package.json
src/App.js
src/components/Codemirror/index.js
src/components/codemirror/index.js
src/constants/routing.js
src/index.js

A feature PR which integrates browser routing
No
Nothign

feat: integrate browser routing in the app

---

src/App.js
src/components/Codemirror/index.js
src/components/CompilerFirstStage/index.js
src/components/codemirror/index.js
src/constants/context.js
src/contexts/index.js

A feature PR which integrates `context + reducer` to share global variables between components like jack code
No
Nothing

feat: setup context and reducer to share global variables

---

package-lock.json
package.json
src/components/Buttons/index.js
src/components/CompilerFirstStage/index.js
src/components/CompilerFirstStage/styled.js
src/components/CompilerFirstStage/util.js
src/components/Header/index.js
src/components/Tokenizer/index.js
src/contexts/index.js

A feature PR which adds a tokenizer simulator
No
Nothing

feat: add tokenizer simulator

---

src/components/Buttons/index.js
src/components/CompilerFirstStage/index.js
src/components/CompilerFirstStage/styled.js

Feature PR which adds back to editor button
No
Nothing

feat: add back to editor button

---

src/components/Codemirror/index.js
src/components/codemirror/index.js

A PR to fix cursor moved to the end after typing a single char in codemirror

fix: codemirror cursor issue

---

src/components/CompilerSecondStage/index.js
src/components/ConceptNote/util.js
src/components/SymbolTable/index.js
src/constants/context.js
src/contexts/index.js

A feature PR which exposes vm output in context

feat: expose vm output in context

---

package-lock.json
package.json
src/App.js
src/abstractions/hardware/ALU/util/index.js
src/abstractions/hardware/Memory/index.js
src/abstractions/hardware/ROM32K/index.js
src/abstractions/software/assembler/code/index.js
src/components/ALU/index.js
src/components/ALU/styled.js
src/components/CPU/ALU/index.js
src/components/CPU/ALU/styled.js
src/components/CPU/ALU/util.js
src/components/CPU/Decoder/index.js
src/components/CPU/Decoder/styled.js
src/components/CPU/Decoder/util.js
src/components/CPU/MemUI/index.js
src/components/CPU/MemUI/styled.js
src/components/CPU/MemUI/util.js
src/components/CPU/Register/index.js
src/components/CPU/Register/styled.js
src/components/CPU/index.js
src/components/CPU/machineInstruction.js
src/components/CPU/styled.js
src/components/CPU/util.js
src/constants/routing.js

A feature PR which adds a CPU simulator
No
Nothing

feat: cpu simulator

---

src/components/CompilerFirstStage/index.js
src/components/CompilerFirstStage/styled.js

fix: modal center issue

---

src/components/ConceptNote/Stack/index.js
src/components/ConceptNote/Stack/styled.js

A fix PR for concept modal issue

fix: concept note modal issue

---

src/App.js
src/components/CPU/styled.js

A feature PR which adds cpu route in navigation
No
Nothing

feat: add cpu route in navigation

---

src/App.js

Fix to change navigation(compiler I and II) colors

fix: change navigation colors

---

src/components/VmSimulator/contexts/modeContext.js
src/components/VmSimulator/hooks/useAsmGenerator.js

fix: do not wait for asm next click when not step simulating

---

src/App.js
src/components/DrawerItem/styled.js

Fix Nav Bar

---

src/abstractions/software/vm-translator/index.js
src/components/VmSimulator/hooks/useAsmGenerator.js

fix: do not generate asm when looping

---

src/components/VmSimulator/hooks/useSegmentReducer.js

fix: hvm not updating ram

---

src/App.js
src/abstractions/software/assembler/symbolTable/index.js
src/abstractions/software/assembler/writer/index.js
src/components/Assembler/FirstPass/index.js
src/components/Assembler/FirstPass/styled.js
src/components/Assembler/SecondPass/Instructions/AInstruction.js
src/components/Assembler/SecondPass/Instructions/CInstruction.js
src/components/Assembler/SecondPass/Instructions/Example.js
src/components/Assembler/SecondPass/Instructions/index.js
src/components/Assembler/SecondPass/Instructions/styled.js
src/components/Assembler/SecondPass/Instructions/util.js
src/components/Assembler/SecondPass/index.js
src/components/Assembler/SecondPass/styled.js
src/components/Assembler/SymbolTableUI/index.js
src/components/Assembler/SymbolTableUI/styled.js
src/components/Assembler/index.js
src/components/Assembler/styled.js
src/components/CPU/MemUI/styled.js
src/constants/context.js
src/constants/routing.js
src/contexts/index.js

A feature PR which adds an assembler simulator 
No
Nothing

feat: add assembler simulator

---

src/components/Assembler/SecondPass/Instructions/styled.js
src/components/Assembler/SecondPass/index.js
src/components/Assembler/SecondPass/styled.js
src/components/Assembler/index.js
src/components/Assembler/styled.js
src/components/CPU/MemUI/index.js
src/components/CPU/MemUI/styled.js
src/components/CPU/index.js

fix: many issues

---

src/components/Assembler/SecondPass/Instructions/index.js
src/components/Assembler/SecondPass/index.js
src/components/Assembler/SecondPass/styled.js
src/components/Assembler/index.js
src/components/Assembler/styled.js

Feat PR to add description in assembler

feat: add assembler description

---

src/App.js
src/components/DrawerItem/styled.js

fix: drawer colors

---

src/abstractions/software/compiler/compilationEngine/index.js
src/components/Codemirror/index.js
src/components/Codemirror/util.js

Feat PR to add description in assembler
Fix PR to wait statements

fix: add await in statements

---

src/contexts/index.js

fix: change assembly context
